module com.example.aims {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires java.naming;
//    requires javafx.swing;
    requires org.controlsfx.controls;
    requires javafx.web;
    requires org.hibernate.orm.core;
    requires java.persistence;
    requires static lombok;
    requires java.sql;
    requires mysql.connector.java;
    requires com.google.gson;
    requires java.transaction;
    requires org.apache.commons.validator;
    requires com.google.api.client.auth;
    requires com.google.api.client.extensions.java6.auth;
    requires com.google.api.client.extensions.jetty.auth;
    requires google.api.client;
    requires com.google.api.client;
    requires com.google.api.client.json.gson;
    requires com.google.api.services.gmail;
    requires org.apache.commons.codec;
    requires mail;
    requires javafx.swing;
    requires org.apache.tomcat.embed.core;
    opens com.example.aims.view to javafx.fxml;
    exports com.example.aims.view;
    opens com.example.aims to javafx.graphics;
    opens com.example.aims.controller;
    opens com.example.aims.entity.media;
    opens com.example.aims.entity.delivery;
    opens com.example.aims.entity.payment;
    exports com.example.aims.view.media;
    opens com.example.aims.view.media to javafx.fxml;
    opens com.example.aims.entity.user;
	exports com.example.aims.view.payment;
    opens com.example.aims.view.payment to javafx.fxml;
    exports com.example.aims.view.delivery;
    opens com.example.aims.view.delivery to javafx.fxml;
    exports com.example.aims.view.cart;
    opens com.example.aims.view.cart to javafx.fxml;
    opens com.example.aims.mail;
    opens com.example.aims.mail.gmail;
    opens com.example.aims.entity.cart;
    opens com.example.aims.entity.order;
    opens com.example.aims.entity to org.hibernate.orm.core;
    exports com.example.aims.utils;
    opens com.example.aims.utils to javafx.fxml;
}